"""
FastAPI ML prediction service for MentorX.
Run: uvicorn api:app --host 0.0.0.0 --port 8000

Expects risk_classifier.pkl, cgpa_regressor.pkl, scaler.pkl
in the same directory (generated by ml model.py).
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import joblib
import numpy as np
import os

app = FastAPI(title="MentorX ML API", version="1.0.0")

# ── Load models at startup ─────────────────────────────────
MODEL_DIR = os.path.dirname(os.path.abspath(__file__))

try:
    clf    = joblib.load(os.path.join(MODEL_DIR, "risk_classifier.pkl"))
    reg    = joblib.load(os.path.join(MODEL_DIR, "cgpa_regressor.pkl"))
    scaler = joblib.load(os.path.join(MODEL_DIR, "scaler.pkl"))
except FileNotFoundError as e:
    raise RuntimeError(
        f"Model file not found: {e}. "
        "Run `python ml\\ model.py` first to train and save the models."
    )

# ── Feature order must match training ─────────────────────
FEATURES = ["cgpa", "attendance", "mood_score", "backlog_count", "placement_encoded"]

PLACEMENT_MAP = {
    "Not Started": 0,
    "Preparing": 1,
    "Applied": 2,
    "Interview Stage": 3,
    "Placed": 4,
}

RISK_LABELS = {0: "Green", 1: "Yellow", 2: "Red"}

SUGGESTIONS = {
    "Green": "Student is performing well. Continue regular monitoring.",
    "Yellow": "Student needs attention. Schedule a check-in meeting and set short-term goals.",
    "Red": "Immediate intervention required. Contact student, parents, and arrange academic support.",
}


# ── Request / Response schemas ─────────────────────────────
class PredictRequest(BaseModel):
    cgpa: float = Field(..., ge=0, le=10)
    attendance: float = Field(..., ge=0, le=100)
    mood_score: int = Field(..., ge=1, le=5)
    backlog_count: int = Field(..., ge=0)
    placement_status: str = Field(default="Not Started")


class PredictResponse(BaseModel):
    risk: str
    risk_probability: float
    predicted_cgpa: float
    suggestion: str


# ── Routes ─────────────────────────────────────────────────
@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest):
    placement_encoded = PLACEMENT_MAP.get(req.placement_status, 0)

    features = np.array([[
        req.cgpa,
        req.attendance,
        req.mood_score,
        req.backlog_count,
        placement_encoded,
    ]])

    try:
        scaled   = scaler.transform(features)
        risk_idx = int(clf.predict(scaled)[0])
        proba    = clf.predict_proba(scaled)[0]
        pred_cgpa = float(round(reg.predict(scaled)[0], 2))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {e}")

    risk_label = RISK_LABELS.get(risk_idx, "Green")

    # risk_probability = probability of the predicted class
    risk_prob = float(round(proba[risk_idx] * 100, 1))

    return PredictResponse(
        risk=risk_label,
        risk_probability=risk_prob,
        predicted_cgpa=min(pred_cgpa, 10.0),
        suggestion=SUGGESTIONS[risk_label],
    )